version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: tour_api_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: tour_db
    ports:
      - '5555:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: